<a href="https://colab.research.google.com/github/qazalkz/NHANES/blob/main/coursera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a= np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(3,)


In [ ]:
print(a[0],a[1],a[2])

1 2 3


In [ ]:
b=np.array([[1,2], [3,4]])
print(b.shape)

(2, 2)


In [ ]:
print(b)

[[1 2]
 [3 4]]


In [ ]:
print(np.shape(b))

(2, 2)


In [ ]:
b[1,0]

3

In [ ]:
c=np.zeros((3,2))
print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
d=np.ones((3,2))
print(d)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
e= np.full((3,3),9)
print(e)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
f=np.random.random((3,3))
print(f)

[[0.15233202 0.08642519 0.88583058]
 [0.15766613 0.0093136  0.88288227]
 [0.11979456 0.90807781 0.40468293]]


In [ ]:
h=np.array([[1,2,3,4],[5,6,7,8],[9,1,11,12]])
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  1 11 12]]


In [ ]:
h=h[ :2,1: 3]
print(h)

[[2 3]
 [6 7]]


In [ ]:
h=np.array([[1,2,3,4],[5,6,7,8],[9,1,11,12]])
i=h[ :2,1: 3]
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  1 11 12]]


In [ ]:
print(i)

[[2 3]
 [6 7]]


In [ ]:
i[0,0]=500
print(h)

[[  1 500   3   4]
 [  5   6   7   8]
 [  9   1  11  12]]


In [ ]:
j=np.array([1,2])
print(j.dtype)
k=np.array([1.0,2.0])
print(k.dtype)
l=np.array([1.0,2.0],dtype=np.int64)
print(l.dtype)

int64
float64
int64


In [ ]:
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [ ]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [ ]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
np.sum(x)

10.0

In [ ]:
np.sum(x , axis=0)

array([4., 6.])

In [ ]:
np.sum(x , axis=1)

array([3., 7.])

In [ ]:
from scipy import stats
import numpy as np


In [ ]:
print(stats.norm.rvs(size=10))

[-1.47961226  0.57910918  1.06477095 -0.13213005 -2.32416636  2.54481984
  2.16631165  0.2304142   1.22295213  0.46118611]


In [ ]:
np.random.seed(1234)
x=stats.t.rvs(10,size=1000)

In [ ]:
print(x.min())

-3.7081318682862507


In [ ]:
print(x.max())

5.489762351653657


In [ ]:
print(x.mean())

0.03301501424446721


In [ ]:
print(x.var())

1.216841589019068


In [ ]:
stats.describe(x)

DescribeResult(nobs=1000, minmax=(-3.7081318682862507, 5.489762351653657), mean=0.03301501424446721, variance=1.2180596486677358, skewness=0.017360162164788, kurtosis=0.9792361694613958)